apiVersion: apps/v1
kind: Deployment
metadata:
  name: experimental
spec:
  replicas: 1
  selector:
    matchLabels:
      name: experimental
  template:
    metadata:
      labels:
        name: experimental
    spec:
      serviceAccountName: experimental
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: 084207842491.dkr.ecr.eu-west-2.amazonaws.com/experimental-operator:v0.0.1
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: 084207842491.dkr.ecr.eu-west-2.amazonaws.com/experimental-operator:v0.0.1
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "experimental"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
